### PR TITLE
Refactor search from cloudsearch to elasticsearch

### PR DESCRIPTION
**Pull request by Gathondu**
#### What does this PR do?
Refactors the API to search from elastic search
#### Description of Task to be completed?
Replace Cloudsearch on HealthTools API with ElasticSearch
#### How should this be manually tested?
run posttests --nocapture

### CODE REVIEW

**Comment by Gathondu** [comment]
@DavidLemayian ☝️ don't know why I can't add you as a reviewer

**Comment by DavidLemayian** [comment]
@Gathondu Did you pull the changes before sending this?

**Comment by Gathondu** [comment]
@DavidLemayian yes I did. And I noticed there is no develop branch that's why I requested against master

**Comment by Gathondu** [comment]
@DavidLemayian let me refactor this to also allow to run from local instance of elastic search

**Comment by Gathondu** [comment]
@DavidLemayian We are good to go 👍

**Pull request closed without merging**
