### PR TITLE
Remove "Nonetype" error when doc_type is not provided

### PR DESCRIPTION
**Pull request by TinaMurimi**
#### What does this PR do?
If a doc_type is not provided or an unknown doc_type is provided, an error is raised because doc_type==None. This PR corrects this error.

### CODE REVIEW

**Comment by DavidLemayian** [comment]
I think the easiest fix to this would be to check [here](https://github.com/CodeForAfricaLabs/HealthTools.API/blob/master/healthtools/views/search_api.py#L12) and return some failed status.

Bonus points: If you get it to work with [this](https://github.com/CodeForAfricaLabs/HealthTools.API/blob/master/healthtools/views/search_api.py#L16).

Also `healthtools/manage.py → manage.py`.. No.

**Comment by TinaMurimi** [comment]
Ok. Will work on that.

**Comment by TinaMurimi** [comment]
@DavidLemayian If we check if the query is passed at base_api, we will miss out on returning all results for the doc_type.

**Comment by DavidLemayian** [comment]
@tinamorale I thought about it and search endpoint should return a null/fail for missing parameter/argument. If we'd like to return all results for the doc_type, it would be a different end-point.

**Pull request closed without merging**
